name: Build Pages
on: [push]
permissions:
  contents: write
jobs:
  build_pages:
    runs-on: ubuntu-latest
    name: Build Pages
    steps:
      - uses: actions/checkout@v2
      - id: Build-Pages
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'devopsirc'
          reponame: 'devopsirc.github.io'
          token: ${{ secrets.GITHUB_TOKEN }}
